# Eclipse Framework Database Configuration
# Supported types: mysql, sqlite, json

# Database type to use
type: "json"

# MySQL Configuration
mysql:
  host: "localhost"
  port: 3306
  database: "eclipse"
  username: "root"
  password: ""

# SQLite Configuration
sqlite:
  # Database filename (will be created in plugin folder)
  filename: "eclipse.db"

# JSON Storage Configuration
json:
  # Main data filename
  filename: "data.json"