# Eclipse Framework Security Configuration

# Rate Limiting Settings
rate-limiting:
  # General rate limits
  general:
    # Maximum logins per minute per IP
    max-logins-per-minute: 10

    # Maximum commands per second per player
    max-commands-per-second: 5

    # Maximum chat messages per second per player
    max-chat-per-second: 3

# Command Cooldowns (in milliseconds)
cooldowns:
  # Default cooldowns for common commands
  tp: 2000
  teleport: 2000
  home: 5000
  spawn: 3000
  back: 10000
  kit: 30000
  heal: 60000
  feed: 30000
  fly: 5000

# Anti-Spam Settings
anti-spam:
  # Enable anti-spam protection
  enabled: true

  # Spam detection threshold (similar messages)
  threshold: 3

  # Time window for spam detection (milliseconds)
  window: 10000

# IP Blocking Settings
ip-blocking:
  # Enable IP blocking
  enabled: true

  # Automatic blocking settings
  auto-block:
    # Enable automatic IP blocking
    enabled: true

    # Number of violations before auto-block
    violation-threshold: 5

    # Auto-block duration in milliseconds (1 hour)
    duration: 3600000